use_frameworks!

platform :ios, '12.0'

target 'Streamoji_Example' do
  pod 'Streamoji', :path => '../'

  target 'Streamoji_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
               end
          end
   end
end
